# TODO I feel like the wording on this is a little clunky and/or ethereal.
# TODO we have is release vs should release and I don't feel like it's clear what the answer is
name: Should release
description: Determines if the current workflow should spawn a something that Jordan can figure out the wording for
outputs:
    should_release:
        description: Returns true if this branch needs should spawn a something that Jordan can figure out the wording for, otherwise false
        value: ${{ steps.determine_should_release.outputs.should_release }}
runs:
    using: composite
    steps:
        - uses: actions/checkout@v4

        - id: determine_should_release
          run: |
              BRANCH_NAME="${{ github.head_ref }}"
              RELEASE_VERSION="${BRANCH_NAME:9}"
              COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
              IS_RELEASE="${{ contains(github.head_ref, 'release--') }}"

              SHOULD_RELEASE="false"
              if [[ $IS_RELEASE == "true" && "$COMMIT_MESSAGE" == "azle-bot automated release $RELEASE_VERSION" ]]; then
                  SHOULD_RELEASE="true"
              fi

              echo "should_release=${SHOULD_RELEASE}" >> "$GITHUB_OUTPUT"
          shell: bash
