name: 'Determine Test Exclusions'
description: 'Determines which tests should be excluded based on workflow trigger and conditions'

inputs:
    is-workflow-dispatch:
        description: 'Whether this is a workflow dispatch event'
        required: true
    exclude-slow-dispatch-input-value:
        description: 'Workflow dispatch input for excluding slow tests'
        required: true
    exclude-unstable-dispatch-input-value:
        description: 'Workflow dispatch input for excluding unstable tests'
        required: true
    exclude-release-only-dispatch-input-value:
        description: 'Workflow dispatch input for excluding release-only tests'
        required: true
    is_feature_branch_draft_pr:
        description: 'Whether this is a draft PR'
        required: true
    is_feature_branch_pr:
        description: 'Whether this is a feature branch PR'
        required: true
    is_main_branch_push:
        description: 'Whether this is a push to main'
        required: true

outputs:
    exclude-slow:
        description: 'Whether to exclude slow tests'
        value: ${{ steps.determine.outputs.exclude-slow }}
    exclude-unstable:
        description: 'Whether to exclude unstable tests'
        value: ${{ steps.determine.outputs.exclude-unstable }}
    exclude-release-only:
        description: 'Whether to exclude release only tests'
        value: ${{ steps.determine.outputs.exclude-release-only }}

runs:
    using: 'composite'
    steps:
        - id: determine
          shell: bash
          run: |
              if [[ "${{ inputs.is-workflow-dispatch }}" == "true" ]]; then
                echo "exclude-slow=${{ inputs.exclude-slow-dispatch-input-value }}" >> $GITHUB_OUTPUT
                echo "exclude-unstable=${{ inputs.exclude-unstable-dispatch-input-value }}" >> $GITHUB_OUTPUT
                echo "exclude-release-only=${{ inputs.exclude-release-only-dispatch-input-value }}" >> $GITHUB_OUTPUT
              else
                exclude-slow=${{ inputs.is_feature_branch_draft_pr }}
                exclude-unstable=${{ inputs.is_feature_branch_draft_pr == 'true' || inputs.is_feature_branch_pr == 'true' }}
                exclude-release-only=${{ inputs.is_feature_branch_draft_pr == 'true' || inputs.is_feature_branch_pr == 'true' || inputs.is_main_branch_push == 'true' }}

                echo "exclude-slow=$exclude-slow" >> $GITHUB_OUTPUT
                echo "exclude-unstable=$exclude-unstable" >> $GITHUB_OUTPUT
                echo "exclude-release-only=$exclude-release-only" >> $GITHUB_OUTPUT
              fi
