name: 'Process Test Conditions'
description: 'Process all test-related conditions and inputs to determine final test configuration'

inputs:
    is-workflow-dispatch:
        description: 'Whether this is a workflow dispatch event'
        required: true
    exclude-slow-dispatch-input-value:
        description: 'Workflow dispatch input for excluding slow tests'
        required: true
    exclude-unstable-dispatch-input-value:
        description: 'Workflow dispatch input for excluding unstable tests'
        required: true
    exclude-release-only-dispatch-input-value:
        description: 'Workflow dispatch input for excluding release-only tests'
        required: true
    fuzz-dispatch-input-value:
        description: 'Workflow dispatch input for running fuzz tests'
        required: false
        default: 'false'

outputs:
    exclude-slow:
        description: 'Whether to exclude slow tests'
        value: ${{ steps.process-conditions.outputs.exclude-slow }}
    exclude-unstable:
        description: 'Whether to exclude unstable tests'
        value: ${{ steps.process-conditions.outputs.exclude-unstable }}
    exclude-release-only:
        description: 'Whether to exclude release-only tests'
        value: ${{ steps.process-conditions.outputs.exclude-release-only }}
    link-azle:
        description: 'Whether to link to the development version of azle'
        value: ${{ steps.process-conditions.outputs.link-azle }}
    fuzz:
        description: 'Whether to run fuzz tests'
        value: ${{ steps.process-conditions.outputs.fuzz }}

runs:
    using: 'composite'
    steps:
        - id: set-conditions
          uses: ./.github/actions/set_run_conditions

        - id: process-conditions
          shell: bash
          run: |
              if [[ "${{ inputs.is-workflow-dispatch }}" == "true" ]]; then
                echo "exclude-slow=${{ inputs.exclude-slow-dispatch-input-value }}" >> $GITHUB_OUTPUT
                echo "exclude-unstable=${{ inputs.exclude-unstable-dispatch-input-value }}" >> $GITHUB_OUTPUT
                echo "exclude-release-only=${{ inputs.exclude-release-only-dispatch-input-value }}" >> $GITHUB_OUTPUT
                echo "link-azle=${{ inputs.link-azle-dispatch-input-value }}" >> $GITHUB_OUTPUT
                echo "fuzz=${{ inputs.fuzz-dispatch-input-value }}" >> $GITHUB_OUTPUT
              else
                exclude-slow=${{ inputs.is_feature_branch_draft_pr }}
                exclude-unstable=${{ inputs.is_feature_branch_draft_pr == 'true' || inputs.is_feature_branch_pr == 'true' }}
                exclude-release-only=${{ inputs.is_feature_branch_draft_pr == 'true' || inputs.is_feature_branch_pr == 'true' || inputs.is_main_branch_push == 'true' }}

                echo "exclude-slow=$exclude-slow" >> $GITHUB_OUTPUT
                echo "exclude-unstable=$exclude-unstable" >> $GITHUB_OUTPUT
                echo "exclude-release-only=$exclude-release-only" >> $GITHUB_OUTPUT
                  if [[ "${{ steps.set-conditions.outputs.is_main_branch_push_from_release_merge }}" == "true" || \
                        "${{ steps.set-conditions.outputs.is_release_branch_pr }}" == "true" ]]; then
                    echo "include_npm=true" >> $GITHUB_OUTPUT
                  else
                    echo "include_npm=false" >> $GITHUB_OUTPUT
                  fi
                echo "fuzz=false" >> $GITHUB_OUTPUT
              fi
