name: 'Process Test Conditions'
description: 'Process all test-related conditions and inputs to determine final test configuration'

inputs:
    is_workflow_dispatch:
        description: 'Whether this is a workflow dispatch event'
        required: true
    exclude_slow_input:
        description: 'Workflow dispatch input for excluding slow tests'
        required: true
    exclude_unstable_input:
        description: 'Workflow dispatch input for excluding unstable tests'
        required: true
    exclude_release_only_input:
        description: 'Workflow dispatch input for excluding release-only tests'
        required: true
    fuzz_input:
        description: 'Workflow dispatch input for running fuzz tests'
        required: false
        default: 'false'

outputs:
    exclude_slow:
        description: 'Whether to exclude slow tests'
        value: ${{ steps.process-conditions.outputs.exclude_slow }}
    exclude_unstable:
        description: 'Whether to exclude unstable tests'
        value: ${{ steps.process-conditions.outputs.exclude_unstable }}
    exclude_release_only:
        description: 'Whether to exclude release-only tests'
        value: ${{ steps.process-conditions.outputs.exclude_release_only }}
    link_azle:
        description: 'Whether to link to the development version of azle'
        value: ${{ steps.process-conditions.outputs.link_azle }}
    fuzz:
        description: 'Whether to run fuzz tests'
        value: ${{ steps.process-conditions.outputs.fuzz }}

runs:
    using: 'composite'
    steps:
        - id: set-conditions
          uses: ./.github/actions/set_run_conditions

        - id: process-conditions
          shell: bash
          run: |
              if [[ "${{ inputs.is_workflow_dispatch }}" == "true" ]]; then
                echo "exclude_slow=${{ inputs.exclude_slow_input }}" >> $GITHUB_OUTPUT
                echo "exclude_unstable=${{ inputs.exclude_unstable_input }}" >> $GITHUB_OUTPUT
                echo "exclude_release_only=${{ inputs.exclude_release_only_input }}" >> $GITHUB_OUTPUT
                echo "link_azle=${{ inputs.link_azle_input }}" >> $GITHUB_OUTPUT
                echo "fuzz=${{ inputs.fuzz_input }}" >> $GITHUB_OUTPUT
              else
                exclude_slow=${{ inputs.is_feature_branch_draft_pr }}
                exclude_unstable=${{ inputs.is_feature_branch_draft_pr == 'true' || inputs.is_feature_branch_pr == 'true' }}
                exclude_release_only=${{ inputs.is_feature_branch_draft_pr == 'true' || inputs.is_feature_branch_pr == 'true' || inputs.is_main_branch_push == 'true' }}

                echo "exclude_slow=$exclude_slow" >> $GITHUB_OUTPUT
                echo "exclude_unstable=$exclude_unstable" >> $GITHUB_OUTPUT
                echo "exclude_release_only=$exclude_release_only" >> $GITHUB_OUTPUT
                  if [[ "${{ steps.set-conditions.outputs.is_main_branch_push_from_release_merge }}" == "true" || \
                        "${{ steps.set-conditions.outputs.is_release_branch_pr }}" == "true" ]]; then
                    echo "include_npm=true" >> $GITHUB_OUTPUT
                  else
                    echo "include_npm=false" >> $GITHUB_OUTPUT
                  fi
                echo "fuzz=false" >> $GITHUB_OUTPUT
              fi
