name: Parallel Benchmark
on:
    workflow_call:
        inputs:
            directories:
                required: true
                type: string
            exclude-dirs:
                required: false
                type: string
                default: ''
            azle-version:
                required: true
                type: string

        secrets:
            GPG_SIGNING_KEY:
                required: true
            GH_TOKEN:
                required: true
            LASTMJS_GITHUB_TOKEN:
                required: true

jobs:
    prepare-benchmark:
        name: Prepare Benchmark
        runs-on: ubuntu-latest
        env:
            GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }} # All commits must be verified
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        outputs:
            azle-version: ${{ inputs.azle-version }}
            test-infos: ${{ steps.get-test-infos.outputs.test-infos }}
        steps:
            - uses: actions/checkout@v4

            - id: get-test-infos
              uses: ./.github/actions/get_test_infos
              with:
                  directories: ${{ inputs.directories }}
                  exclude-dirs: ${{ inputs.exclude-dirs }}

    run-benchmarks:
        needs: prepare-benchmark
        name: Run benchmarks for ${{ matrix.test.name }}
        runs-on: ubuntu-latest
        env:
            GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        strategy:
            fail-fast: false
            matrix:
                test: ${{ fromJson(needs.prepare-benchmark.outputs.test-infos) }}
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.ref || github.ref }}
                  token: ${{ secrets.LASTMJS_GITHUB_TOKEN || github.token }}

            - uses: ./.github/actions/setup_node

            - uses: ./.github/actions/setup_dfx

            - name: Install dependencies
              run: |
                  npm install
                  cd ${{ matrix.test.path }}
                  npm install

            - name: Start dfx with artificial delay 0
              working-directory: ${{ matrix.test.path }}
              run: dfx start --clean --background --host 127.0.0.1:8000 --artificial-delay 0

            - name: Run npm test (continue on error)
              working-directory: ${{ matrix.test.path }}
              continue-on-error: true
              run: npm test

            - uses: ./.github/actions/configure_git
              with:
                  gpg_signing_key: ${{ secrets.GPG_SIGNING_KEY }}

            - name: Commit and push changes
              run: |
                  BRANCH_NAME="benchmark--${{ needs.prepare-benchmark.outputs.azle-version }}-$(echo '${{ matrix.test.displayPath }}' | sed 's/\//-/g')"
                  git switch -c "$BRANCH_NAME"
                  git add --all
                  if ! git diff --cached --quiet; then
                    git commit -m "Run benchmarks for ${{ matrix.test.displayPath }}"
                  else
                    echo "No changes to commit. Skipping commit and push."
                  fi
                  git push origin "$BRANCH_NAME"
