name: Prepare and Run Tests

on:
    workflow_call:
        inputs:
            directories:
                required: true
                type: string
            exclude-dirs:
                required: false
                type: string
                default: ''
            run-experimental:
                required: false
                type: boolean
                default: false
            fuzz:
                required: false
                type: boolean
                default: false
            link-azle:
                required: true
                type: boolean

jobs:
    prepare-test-environment:
        name: 'Prepare Test Environment'
        runs-on: ubuntu-latest
        outputs:
            test-infos: ${{ steps.get-test-infos.outputs.test-infos }}
        steps:
            - uses: actions/checkout@v4

            - id: get-test-infos
              uses: ./.github/actions/get_test_infos
              with:
                  directories: ${{ inputs.directories }}
                  exclude-dirs: ${{ inputs.exclude-dirs }}

    run-tests:
        name: 'Run'
        needs: prepare-test-environment
        uses: ./.github/workflows/run_test.yml
        with:
            test_infos: ${{ needs.prepare-test-environment.outputs.test-infos }}
            link-azle: ${{ inputs.link-azle }}
            run-experimental: ${{ inputs.run-experimental }}
            fuzz: ${{ inputs.fuzz }}
