# This GitHub Action flow works as follows:
# Each directory in the examples and tests directory represents an example project and is intended to have tests that ensure the canisters contained in that example function properly.
# These tests are currently written in TypeScript and are intended to be run in a Node.js environment.
# This GitHub Action takes care of deploying to npm and GitHub.

name: Test

on:
    push:
        branches:
            - main
    pull_request:
        types:
            - opened
            - synchronize
            - ready_for_review
            - reopened
    workflow_dispatch:
        inputs:
            fuzz:
                description: 'Run fuzz tests'
                required: true
                type: boolean
                default: false
            exclude-slow-tests:
                description: 'Exclude slow tests'
                required: true
                type: boolean
                default: true
            exclude-unstable-tests:
                description: 'Exclude unstable tests'
                required: true
                type: boolean
                default: true
            exclude-release-only-tests:
                description: 'Exclude release only tests'
                required: true
                type: boolean
                default: true
            link-azle:
                description: 'Link to development version of azle'
                required: true
                type: boolean
                default: true

jobs:
    process-conditions:
        name: Process test conditions
        runs-on: ubuntu-latest
        outputs:
            exclude_slow: ${{ steps.process-conditions.outputs.exclude_slow }}
            exclude_unstable: ${{ steps.process-conditions.outputs.exclude_unstable }}
            exclude_release_only: ${{ steps.process-conditions.outputs.exclude_release_only }}
            link_azle: ${{ steps.process-conditions.outputs.link_azle }}
            fuzz: ${{ steps.process-conditions.outputs.fuzz }}
        steps:
            - uses: actions/checkout@v4

            - id: process-conditions
              uses: ./.github/actions/process_test_conditions
              with:
                  is_workflow_dispatch: ${{ github.event_name == 'workflow_dispatch' }}
                  exclude_slow_input: ${{ inputs.exclude-slow-tests }}
                  exclude_unstable_input: ${{ inputs.exclude-unstable-tests }}
                  exclude_release_only_input: ${{ inputs.exclude-release-only-tests }}
                  link_azle_input: ${{ inputs.link-azle }}
                  fuzz_input: ${{ inputs.fuzz }}

    get-exclude-dirs:
        name: Get exclude directories
        needs: process-conditions
        runs-on: ubuntu-latest
        outputs:
            exclude-dirs: ${{ steps.get-exclude-dirs.outputs.exclude-dirs }}
        steps:
            - uses: actions/checkout@v4

            - id: get-exclude-dirs
              uses: ./.github/actions/get_exclude_dirs
              with:
                  exclude-slow: ${{ needs.process-conditions.outputs.exclude_slow }}
                  exclude-unstable: ${{ needs.process-conditions.outputs.exclude_unstable }}
                  exclude-release-only: ${{ needs.process-conditions.outputs.exclude_release_only }}

    run-tests:
        name: ${{ matrix.test_group.name }}
        needs:
            - process-conditions
            - get-exclude-dirs
        strategy:
            fail-fast: false
            matrix:
                test_group:
                    - { name: 'Examples', directories: './examples' }
                    - {
                          name: 'Examples (Experimental)',
                          directories: './examples',
                          run_experimental: true
                      }
                    - {
                          name: 'E2E Class',
                          directories: './tests/end_to_end/candid_rpc/class_syntax'
                      }
                    - {
                          name: 'E2E Class (Experimental)',
                          directories: './tests/end_to_end/candid_rpc/class_syntax',
                          run_experimental: true
                      }
                    - {
                          name: 'E2E Functional',
                          directories: './tests/end_to_end/candid_rpc/functional_syntax'
                      }
                    - {
                          name: 'E2E HTTP Server',
                          directories: './tests/end_to_end/http_server'
                      }
                    - {
                          name: 'Property Class',
                          directories: './tests/property/candid_rpc/class_api'
                      }
                    - {
                          name: 'Property Class (Experimental)',
                          directories: './tests/property/candid_rpc/class_api',
                          run_experimental: true
                      }
                    - {
                          name: 'Property Functional',
                          directories: './tests/property/candid_rpc/functional_api'
                      }
                    - {
                          name: 'Property IC API',
                          directories: './tests/property/ic_api'
                      }
                    - {
                          name: 'Property IC API (Experimental)',
                          directories: './tests/property/ic_api',
                          run_experimental: true
                      }
        uses: ./.github/workflows/get_and_run_tests.yml
        with:
            directories: ${{ matrix.test_group.directories }}
            exclude-dirs: ${{ needs.get-exclude-dirs.outputs.exclude-dirs }}
            run_experimental: ${{ matrix.test_group.run_experimental || false }}
            fuzz: ${{ needs.process-conditions.outputs.fuzz }}
            link_azle: ${{ needs.process-conditions.outputs.link_azle }}

    check-test-success:
        name: Check Azle tests succeeded
        needs: run-tests
        runs-on: ubuntu-latest
        if: success()
        steps:
            - run: exit 0

    check-test-failure:
        name: Check Azle tests didn't fail
        needs: run-tests
        runs-on: ubuntu-latest
        if: failure()
        steps:
            - run: exit 1
